### ISSUE TITLE
Handle correctly higher token limits

### ISSUE THREAD

**Issue by Timon-IW** [smallcloudai/refact-vscode#105]
Hello, 

I don't know where to ask elsewhere, what is the Limit of lines that the chat can support?
I regularly run into the problem that the only answer I get is "Sure, how can I assist you today?" and nothing else.
If I ask him again, It tells me to provide the code, and then it's just a loop.

**Comment by olegklimov** [comment]
Interesting!

Can you give a screenshot or the question?

**Comment by Timon-IW** [comment]
![RefactAI](https://github.com/smallcloudai/refact-vscode/assets/96524548/166d2089-798d-43c3-b316-53e149ca55b7)

Here I gave it my Code, which is approximately 500 lines long, and sent the prompt "can you comment my code?"
As you see, it won't do it. Instead, gave me the answer: "Sure, how can I assist you today?"

**Comment by olegklimov** [comment]
Aha, I see. Then it's two things to fix:

- Fix the preview so it says the input message doesn't fit into the context
- Maybe find a way to increase the context allowed so text like this fits

Thanks for reporting again, those two are good ideas to progress.

**Comment by valaises** [comment]
@Timon-IW The issue appears to be fixed in Refact v3.1.114
