### ISSUE TITLE
"Next" button not working when logging in (VS Code)

### ISSUE THREAD

**Issue by dev-qolaig** [smallcloudai/refact-vscode#115]
I have trouble logging in on VS Code. I copy pasted the token instead of login in manually. But when I click "Next" nothing happens.

**Comment by oxyplay** [comment]
Hello @dev-qolaig, thank you for the issue. Could you please share your os and plugin version? Just checked and it's works.

**Comment by dev-qolaig** [comment]
im on MacOS, Refact v3.1.121

**Comment by hazratisulton** [comment]
v5.0.100 - fixed
