### ISSUE TITLE
Files mentioned by agent in chat should be linked/clickable.

### ISSUE THREAD

**Issue by cardoso** [smallcloudai/refact-vscode#122]
Files mentioned by the agent should be clickable to save time. Example `mutation-tracking.ts` (third line from the bottom):

<img width="653" alt="Screenshot 2024-07-20 at 19 33 14" src="https://github.com/user-attachments/assets/bc2d1e5f-f326-492b-a9e9-e78afe11be7d">

**Comment by olegklimov** [comment]
Of course they should be.

**Comment by olegklimov** [comment]
Completed!
