### ISSUE TITLE
Copy chat messages as rich text or markdown

### ISSUE THREAD

**Issue by cardoso** [smallcloudai/refact-vscode#124]
Currently it's only possible to copy code snippets. It would be useful to have a button to copy the entire message. While it's possible to select and manually copy, it includes the VSCode theme format and whatever is off screen won't be copied (the messages are often large and VSCode needs to be very zoomed out to allow copying everything). The off screen content not being copied is a separate bug in my opinion, but the root cause might be on vscode or the libraries used in the webview.

**Comment by olegklimov** [comment]
Why would you need the entire message?
