### ISSUE TITLE
add: link for vs code extension 

### ISSUE THREAD

**Issue by jaiakash** [smallcloudai/refact-vscode#133]
I noticed that the GitHub repository for this project doesn't currently have a link to the extension. Adding a link to the README file and the repository description would make it easier for users to find and install the extension. This would enhance the overall user experience and promote the project. Right now, we can only find a link to download the extension from the website.

What do you think?

**Comment by olegklimov** [comment]
Er sure, we should fix that.

**Comment by jaiakash** [comment]
I will make a PR for same.
