### ISSUE TITLE
[chat] A specific request freezes up the extension

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-vscode#18]
"write mysql Dockefile that copies config nearby and makes mysql use it"

![image](https://github.com/smallcloudai/refact-vscode/assets/18546213/a322f10c-dd25-4ef9-9ab5-5be8ed44c8a2)

Nothing discernable when trying to stop execution and look at the stack.
"Github authentication provider"?

😕

**Comment by hazratisulton** [comment]
Checked plugin v2.0.127 with gpt-3.5 and gpt-4 - the problem was not reproduced.
