### ISSUE TITLE
перестало работать расширение в VS CODE

### ISSUE THREAD

**Issue by dimaborisevich** [smallcloudai/refact-vscode#19]
Расширение перестало работать в VS CODE. Нажимаю новый чат. окно появляется, но невозможно выбрать модель и сообщение не отправляется
![Снимок экрана от 2023-07-31 23-59-39](https://github.com/smallcloudai/refact-vscode/assets/135470303/9eb0c421-c850-407d-a2eb-c243a05c4428)

**Comment by olegklimov** [comment]
Fixed! Press "refresh", a circular arrow on the left.

Thanks for reporting!
