### ISSUE TITLE
vscode extension turns off autosave

### ISSUE THREAD

**Issue by ElliotReed** [smallcloudai/refact-vscode#23]

**Comment by ohare93** [comment]
Please fix this. This extension turns off Autosave globally, without mentioning that it does so, and with no option to disable it! 😢 

I have autosave enabled everywhere for a good reason: I forget to save things! This makes this extension completely useless to me.

**Comment by ohare93** [comment]
I see the offending line is here https://github.com/smallcloudai/refact-vscode/blob/main/src/fetchAPI.ts#L312 with the comment "// otherwise diffs do not work properly". What exactly does that mean?

**Comment by olegklimov** [comment]
When you paste code from chat using "diff":

<img width="405" alt="image" src="https://github.com/smallcloudai/refact-vscode/assets/18546213/b702e359-b185-40e0-9382-7b10b0df685b">


Autosave will save both red and green text, because it's real text, highlighted as diff by the plugin.

Maybe a better solution exists!

**Comment by uchuhimo** [comment]
Please give us an option to disable it. I only use the code completion, so the diff issue has nothing to do with me.

**Comment by ohare93** [comment]
Completely agreed! I don’t use diff either. Please make it a confit option. Hell, just remove it altogether and add a warning somewhere about disabling auto save if you want the diff to work.

**Comment by olegklimov** [comment]
OK, we'll fix that in the next release next week! Sorry for any inconveniences.

**Comment by ohare93** [comment]
Any idea when the next release will be? 🙏

**Comment by olegklimov** [comment]
Fixed, please try 🎉
