### ISSUE TITLE
[bounty] Chat overhaul

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-vscode#28]
The current chat is this:

<img width="595" alt="image" src="https://github.com/smallcloudai/refact-vscode/assets/18546213/d3949760-7881-4424-9022-cde1b0b4f38e">

The good about it:

* Opens on shortcut (Alt+C)
* Any selected code automatically gets copied into ''' section
* It receives the answer with streaming, autoscroll, markdown
* Code blocks have buttons: `diff`, `new file`, `copy`
* The `retry` button allows to go back and change the question

<img width="598" alt="image" src="https://github.com/smallcloudai/refact-vscode/assets/18546213/5729f895-eb54-4a30-985a-fd8bb7a7c73f">

The bad about it:

* Autoscroll is too invasive: if the answer is still streaming, it will not allow to copy-paste an already useful part of the answer.
* `diff`, `new file`, `copy` are not available until streaming is finished.
* It's better for `retry` button to edit question in place (similar to OpenAI chat UI).
* Code blocks have no syntax highlight.
* Style could be better.

Epic change needed: instead of tabs, use sidebar. Make a new one, to avoid conflicting with the existing sidebar.

* History becomes a button that opens a list previous conversations (similar to Sourcegraph UI)
* After switching to a previous conversation, the user should be able to continue it, or use `retry`
* Chat history should survive IDE restart, stored in globalState or similar

![image](https://github.com/smallcloudai/refact-vscode/assets/18546213/e1ab52ad-420c-4228-afb6-37da4ae68928)
Picture: history in sourcegraph UI

A good solution is:
* Small code, compared to the existing one, or at least not much more
* Clear what's going on, when looking at any given screenful of code

**Comment by mnmt7** [comment]
Hey @aazam-gh, I see you are already taking care of [support for LSP 3.18 InlineCompletion](https://github.com/smallcloudai/refact-lsp/issues/1). Do you mind if I work on this one?

**Comment by aazam-gh** [comment]
Hi @mnmt7 you can go for the LSP support one instead. I'll handle this one then :)

**Comment by lalitkumawat1m** [comment]
Hello beautiful people,
I'm a beginner in open source contributor.
Could you please tell me more about this issue?

**Comment by aazam-gh** [comment]
@olegklimov Since we are implementing a sidebar does that mean we will be having a total of two sidebars? One for the Refact: AI toolbox and the other for the Chat? Should clicking on `New Chat` then open another tab or instead open another sidebar itself?

**Comment by olegklimov** [comment]
> total of two sidebars

Yes. Eventually there should be one, but for the purpose of this task, it's better to have it separate, avoid scope drift.


> clicking on New Chat .. open another sidebar itself

Should open new chat in the sidebar. The existing chat should go into history, accessible via history button.

**Comment by aazam-gh** [comment]
Gotcha, so first I should start by making the chat into a side bar and opening new chats in it

**Comment by aazam-gh** [comment]
@olegklimov According to the docs, Idont think it's possible to add views to a secondary sidebar.
https://code.visualstudio.com/api/ux-guidelines/sidebars#secondary-sidebar
It would be better to open the chat within the current sidebar itself in my opinion. What are your thoughts?

**Comment by olegklimov** [comment]
> views to a secondary sidebar

Maybe another primary sidebar?


> within the current sidebar itself in my opinion

It's not something we want to be stuck at. Eventually there should be 1 sidebar for the plugin, for the purpose of this task the idea is to minimize intervention to any code unrelated to chat.

**Comment by Ahmadkhan02** [comment]
/attempt #28
@olegklimov 

> > views to a secondary sidebar
> 
> Maybe another primary sidebar?
> 
> > within the current sidebar itself in my opinion
> 
> It's not something we want to be stuck at. Eventually there should be 1 sidebar for the plugin, for the purpose of this task the idea is to minimize intervention to any code unrelated to chat.

VS code wont allow for direct addition to a secondary sidebar. How about we directly add chat to the plugin in the primary once the rest of the issue is solved?

**Comment by aazam-gh** [comment]
@olegklimov for the autoscroll being too invasive. What is your opinion on the following change
```
let autoScrollTimeout;
function auto_scroll() {
  if (autoScrollTimeout) {
    return;
  }

  autoScrollTimeout = setTimeout(() => {
    input_care();
    currentHeight.scrollTop = currentHeight.scrollHeight;
    autoScrollTimeout = null;
  }, 100); 
}
```
This would make it scroll with a delay

**Comment by feliciien** [comment]
Hello, I would like to work on this if anyone wants to collaborate with and split the bounty there is my discord username feliciien /attempt #28.

**Comment by aazam-gh** [comment]
Hi I'm already working on this and will be making a pr soon

**Comment by Ahmadkhan02** [comment]
@olegklimov I am done with all tasks but the sidebar one which I am not clear about. As I stated earlier I a new sidebar would work for chat. Tell me your thought about it. I'll open a pull request though

**Comment by Ahmadkhan02** [comment]
@olegklimov Hope you liked the pr and thanks!!
