### ISSUE TITLE
how to setup this project for local development?

### ISSUE THREAD

**Issue by Ashu999** [smallcloudai/refact-vscode#30]
don't see any local development/contribution guide

I already have refact-vsocde extension installed, any chance that there might be conflict between them (I have not worked on an vs-code extension before)

**Comment by Ahmadkhan02** [comment]
hi @Ashu999 just run the program via vs code. It will open a development environment and that would not be conflicting with the existing extension

**Comment by Ashu999** [comment]
thanks
