### ISSUE TITLE
Consider dropping support for Mac (saves dev time)

### ISSUE THREAD

**Issue by abebeos** [smallcloudai/refact-vscode#38]
Re https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/#:~:text=Visual%20Studio%20for%20Mac%20will,longer%20be%20serviced%20or%20maintained.

**Comment by olegklimov** [comment]
It's not VS Classic, it's VS Code :D 
We'll have VS Classic hopefully soon, but it's not this project.
