### ISSUE TITLE
404 page not found for https://refact.smallcloud.ai/waiting-list

### ISSUE THREAD

**Issue by Gorrrg** [smallcloudai/refact-vscode#44]
I'm trying to login to refact.ai with my github account, but the page I get redirected to doesn't exist.

**Comment by oxyplay** [comment]
@Gorrrg Could you please reset cookies and try now to login and accept Terms of Use. https://refact.smallcloud.ai/terms?redirect=free. You got some strange status like something was wrong in the middle of registration.
