### ISSUE TITLE
can not login  

### ISSUE THREAD

**Issue by Maziar123** [smallcloudai/refact-vscode#47]
Hi

Use vscode in linux, tried to activate Cloud mode v1.0.52 after the browser showed a successful login 
refact continues to show waiting for login  

Also, refact doesn't show a message in the vscode output. 
Have a log file?

**Comment by hazratisulton** [comment]
v5.0.100 - not reproducible.
Please update to v5.0.100

**Comment by Maziar123** [comment]
current fix
