### ISSUE TITLE
Refact v1.0.1026 only have gpt 3.5 turbo & limit to copy paste large text 

### ISSUE THREAD

**Issue by Maziar123** [smallcloudai/refact-vscode#48]
via need support http_proxy i use pre-release version v1.0.1026

I use in Linux vscode

1. only gpt3.5 turbo in model (no gpt-4)
2. It seems manually entering the key for key-based activation does not work
3. I have problem /limit to copy paste large text in chat seems hard limited

**Comment by hazratisulton** [comment]
v5.0.100 - not reproducible
