### ISSUE TITLE
[VS Code] Migrate refactai.infurl to refactai.adressURL

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact-vscode#67]
Usind self-hosted ot enterpise and have setup infurl something like http://127.0.0.1:8008
Switched from release v1.3.0 to pre-release v2.0.102.
Expected result: Plugin continue working
Actual result: Plugin not working, because infurl abandoned and new field Adress URL is empty

**Comment by olegklimov** [comment]
fixed 2.0.104
