### ISSUE TITLE
Failed To Load Tokenizer: EOF 

### ISSUE THREAD

**Issue by artforlife** [smallcloudai/refact-vscode#69]
I have installed Refact as a self-hosted instance. It mostly appears to work, but there is an issue. When using the model combination below and typing code, the VS Code plugin returns the following error

`failed to load tokenizer: EOF while parsing a value at line 1 column 0`

Upon inspecting the logs, one can discover that this happens because instead of getting a tokenizer file with JSON in it, the file is empty or does not exist. For instance, for the model named StarCoder and for the VSCodium web version, the following file would be missing

`/home/coder/.cache/refact/tokenizers/starcoder/15b/plus/tokenizer.json `

That is, it appears that the Refact plugin is somehow not loading the tokenizers correctly. Whenever the file is added manually, requests begin working without error.

<img width="1329" alt="Screenshot 2023-12-05 at 16 39 28" src="https://github.com/smallcloudai/refact-vscode/assets/8064423/8429d8cd-1870-46cc-ae29-923184519125">

**Comment by olegklimov** [comment]
We've seen something like this before. But I thought it was fixed, with a change that adds .flush() when downloading a tokenizer file.

**Comment by mitya52** [comment]
@artforlife we need your plugin version, this should be be fixed in the latest one

**Comment by hazratisulton** [comment]
- Checked plugin v2.0.127 with broken, empty and non existing tokenizer.json - new tokenizer is downloading without problems.
