### ISSUE TITLE
Why can't my refact.ai complete the code

### ISSUE THREAD

**Issue by asky2083664719** [smallcloudai/refact-vscode#71]
Why can't my refact.ai complete the code.
I'm free user

**Comment by asky2083664719** [comment]
![image](https://github.com/smallcloudai/refact-vscode/assets/47145997/5214d000-3d40-4401-954c-6fefbc0560d8)

**Comment by olegklimov** [comment]
That's a chat on the left, in the sidebar, not code. Try typing inside the editor. You can see Refact status bar icon at the bottom, when it fetched code completion you'll see there a rotating icon.

**Comment by olegklimov** [comment]
let us know if there's a bug
