### ISSUE TITLE
[VS Code] Change from LSP to HTTP in telemetry

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-vscode#78]
Issues we have with LSP that we don't have with HTTP:
* some filetypes telemetry is being ignored
* short completions may not be counted in

What we have to do is:
on did change use HTTP request instead of relying on LSP

33 lines of code completed in cpp file, but there is no stats:
![Image](https://github.com/smallcloudai/refact-vscode/assets/140423660/522641eb-daa1-45f4-a3e1-3191c62bbf0f)

**Comment by olegklimov** [comment]
> some filetypes telemetry is being ignored
Which? Why?

> short completions may not be counted
That we already send via http?
