### ISSUE TITLE
Ошибка The RUST LSP server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by avk1702** [smallcloudai/refact-vscode#82]
При загрузке Visual Studio Code с установленным Refact выводится Ошибка The RUST LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. В расширении Refact выбрать use model не возможно, запрос не отправляется

**Comment by olegklimov** [comment]
Hi @avk1702 
Is it windows, linux, mac?
Can you find any logs here:
```
tail -f -n 1000 ~/.cache/refact/logs/rustbinary.2024-01-12
```
?
If there's nothing, maybe you can find anything useful in VS Code: "Help" / "Toggle Developer Tools" / "Console" ?
Another thing to try: find refact-lsp executable, it's `./.vscode/extensions/smallcloud.codify-2.0.119-darwin-arm64/assets/refact-lsp` on my computer, and just try to run it, for example with "--help", will it run at all?

**Comment by olegklimov** [comment]
Hey @avk1702 but what was it?
