### ISSUE TITLE
Cannot move toolbox

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-vscode#9]
"An error"

**Comment by olegklimov** [comment]
This bug is still present
<img width="395" alt="image" src="https://github.com/smallcloudai/refact-vscode/assets/18546213/4253c4ac-14d1-4d51-b340-c213cb31466a">

**Comment by olegklimov** [comment]
But "error" disappears after IDE restart.

**Comment by hazratisulton** [comment]
Not relevant after reworking toolbox in plugin versions v2.
